import 'package:flutter/material.dart';
import 'models.dart';

final List<Collection> mockCollections = [
  const Collection(id: 'wl', name: 'Watch later', emoji: '🎬'),
  const Collection(id: 'news', name: 'News', emoji: '📰'),
  const Collection(id: 'recipes', name: 'Recipes', emoji: '🍕'),
  const Collection(id: 'startup', name: 'Startup', emoji: '💡'),
  const Collection(id: 'music', name: 'Music', emoji: '🎵'),
  const Collection(id: 'kdrama', name: 'Korean TV series', emoji: '🎭'),
];

final List<LinkItem> mockLinks = [
  LinkItem(
    id: 1,
    title: 'Watch K-Dramas, Korean Shows & Chinese Dramas | Rakuten Viki',
    domain: 'viki.com',
    collectionId: 'kdrama',
    date: 'Apr 11, 2026',
    thumbBg: const Color(0xFF0A2820),
    thumbEmoji: '🎬',
    description: 'Stream Korean dramas and other Asian content with subtitles on Viki.',
  ),
  LinkItem(
    id: 2,
    title: 'How to start a startup: a practical guide',
    domain: 'e-resident.gov.ee',
    collectionId: 'startup',
    date: 'Apr 11, 2026',
    thumbBg: const Color(0xFF101028),
    thumbEmoji: '💡',
    description: 'A step-by-step guide to launching your startup from idea to incorporation.',
  ),
  LinkItem(
    id: 3,
    title: 'King The Land Episode 1 in Hindi/Urdu Dubbing Korean Drama',
    domain: 'youtu.be',
    collectionId: 'kdrama',
    date: 'Apr 11, 2026',
    thumbBg: const Color(0xFF280A0A),
    thumbEmoji: '▶',
    description: 'Watch King The Land Episode 1 fully dubbed in Hindi/Urdu.',
  ),
  LinkItem(
    id: 4,
    title: 'Balsamic Chicken and Mushrooms',
    domain: 'allrecipes.com',
    collectionId: 'recipes',
    date: 'Apr 11, 2026',
    read: true,
    favorite: true,
    thumbBg: const Color(0xFF281408),
    thumbEmoji: '🍗',
    description: 'A rich balsamic-glazed chicken recipe with sautéed cremini mushrooms.',
  ),
  LinkItem(
    id: 5,
    title: 'Sam Altman responds to the AI safety crisis',
    domain: 'techcrunch.com',
    collectionId: 'news',
    date: 'Apr 11, 2026',
    thumbBg: const Color(0xFF081828),
    thumbEmoji: '📰',
    description: 'Sam Altman addresses growing AI safety concerns in a detailed statement.',
  ),
  LinkItem(
    id: 6,
    title: 'How I Tricked The Internet',
    domain: 'youtu.be',
    collectionId: 'wl',
    date: 'Apr 10, 2026',
    thumbBg: const Color(0xFF1A0808),
    thumbEmoji: '📹',
    description: 'A deep-dive into how viral misinformation spreads and gets exploited.',
  ),
  LinkItem(
    id: 7,
    title: 'Lo-fi beats to study and relax to — 24/7 stream',
    domain: 'open.spotify.com',
    collectionId: 'music',
    date: 'Apr 9, 2026',
    favorite: true,
    thumbBg: const Color(0xFF081A10),
    thumbEmoji: '🎵',
    description: 'Chill lo-fi hip hop playlist for focus and relaxation. Updated weekly.',
  ),
];
